language: android
android:
  components:
    # Descomentar lo siguiente pars usar la ultima version de Android SDK Tools
    - tools
    - platform-tools

    # Version de las BuildTools usadas para compilar el proyecto
    # Mirar en Settings -> Android SDK -> SDK tools -> show package details
    #- build-tools-28.0.2

    # Version del SDK usada para compilar el proyecto
    #- android-26

    # Componentes adicionales
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

    # Para ejecutar el emulador en los tests
    # Indicar al menos una imagen
    #- sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-21
    
# Exporta las licencias aceptadas en nuestro ordenador
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'