language: android
android:
  components:
    # Descomentar lo siguiente pars usar la ultima version de Android SDK Tools
    #- tools
    #- platform-tools

    # Version de las BuildTools usadas para compilar el proyecto
    # Mirar en Settings -> Android SDK -> SDK tools -> show package details
    - build-tools-27.0.3

    # Version del SDK usada para compilar el proyecto
    - android-26

    # Componentes adicionales
    #- extra-google-google_play_services
    #- extra-google-m2repository
    #- extra-android-m2repository
    #- addon-google_apis-google-26

    # Para ejecutar el emulador en los tests
    # Indicar al menos una imagen
    - sys-img-armeabi-v7a-android-26
    #- sys-img-armeabi-v7a-android-21

# Exporta las licencias aceptadas en nuestro ordenador
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

# Emulator Management: Create, Start and Wait
before_script:
  - echo no | android create avd --force -n test -t android-26 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ./gradlew connectedAndroidTest
